# Generated by Django 3.0.3 on 2020-03-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200229_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0.0, help_text='price'),
        ),
        migrations.AddField(
            model_name='item',
            name='product_id',
            field=models.IntegerField(default=0, help_text='product id'),
        ),
        migrations.AddField(
            model_name='item',
            name='product_name',
            field=models.CharField(help_text='product name', max_length=200, null=True, verbose_name='Product Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Email', max_length=100, null=True, verbose_name='Email ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='First Name', max_length=20, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='Last Name', max_length=20, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Password', max_length=20, null=True, verbose_name='Password'),
        ),
    ]
